"""Настройки размеров и оформления GUI."""

# Размеры главного окна и базового шрифта приложения.
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 800
WINDOW_MIN_WIDTH = 1000
WINDOW_MIN_HEIGHT = 650
APP_FONT_POINT_SIZE = 10

# Общие отступы для корневого layout, вкладок и вложенных панелей.
ROOT_MARGINS = (12, 10, 12, 10)
ROOT_SPACING = 8
TAB_MARGINS = (4, 8, 4, 4)
TAB_SPACING = 10
ZERO_MARGINS = (0, 0, 0, 0)

# Вертикальные пропорции блоков на вкладке источника данных.
SOURCE_GROUP_STRETCH = 1
TASKS_GROUP_STRETCH = 4

# Горизонтальные пропорции колонок формы параметров алгоритма.
ALGORITHM_LEFT_STRETCH = 1
ALGORITHM_RIGHT_STRETCH = 2

# Пропорции и начальные размеры областей на вкладке запуска.
RUN_UPPER_HISTORY_STRETCH = 3
RUN_UPPER_CHART_STRETCH = 7
RUN_UPPER_INITIAL_SIZES = [300, 700]
RUN_LOWER_INFO_STRETCH = 13
RUN_LOWER_PLOT_STRETCH = 27
RUN_LOWER_INITIAL_SIZES = [325, 675]
RUN_VERTICAL_TOP_STRETCH = 3
RUN_VERTICAL_BOTTOM_STRETCH = 2

# Минимальные ширины часто повторяемых управляющих элементов.
CONTROL_BUTTON_MIN_WIDTH = 130
GANTT_TOOL_BUTTON_MIN_WIDTH = 42
COMBO_MIN_WIDTH = 220

# Начальное состояние таблицы задач.
TASK_TABLE_INITIAL_ROWS = 12
TABLE_ERROR_COLOR = "#ef4444"

# Диапазоны и значения по умолчанию для параметров алгоритма.
POPULATION_RANGE = (2, 100000)
POPULATION_DEFAULT = 80
GENERATIONS_RANGE = (1, 10000)
GENERATIONS_DEFAULT = 50
PROBABILITY_RANGE = (0.0, 1.0)
CROSSOVER_PROBABILITY_STEP = 0.05
CROSSOVER_PROBABILITY_DEFAULT = 0.85
MUTATION_PROBABILITY_STEP = 0.01
MUTATION_PROBABILITY_DEFAULT = 0.12
RANDOM_TASK_COUNT_RANGE = (1, 200)
RANDOM_TASK_COUNT_DEFAULT = 12
DURATION_RANGE = (1, 1000)
MIN_DURATION_DEFAULT = 1
MAX_DURATION_DEFAULT = 12
DEADLINE_RANGE = (1, 10000)
MIN_DEADLINE_DEFAULT = 8
MAX_DEADLINE_DEFAULT = 60
ELITE_COUNT_RANGE = (0, 100000)
ELITE_COUNT_DEFAULT = 1
TOURNAMENT_SIZE_RANGE = (1, 100000)
TOURNAMENT_SIZE_DEFAULT = 3
STAGNATION_LIMIT_RANGE = (0, 100000)
STAGNATION_LIMIT_DEFAULT = 0
SEED_RANGE = (0, 2_147_483_647)
SEED_DEFAULT = 42

# Базовые размеры диаграммы Ганта.
GANTT_MIN_HEIGHT = 170
GANTT_EMPTY_SCENE = (0, 0, 320, 120)
GANTT_LEFT_MARGIN = 58
GANTT_TOP_MARGIN = 38
GANTT_ROW_HEIGHT = 34
GANTT_BAR_HEIGHT = 22
GANTT_MIN_WIDTH = 900
GANTT_TIME_SCALE = 30
GANTT_EXTRA_RIGHT_SPACE = 140
GANTT_TICK_COUNT = 12
GANTT_MIN_BAR_WIDTH = 18
GANTT_ZOOM_STEP = 1.2
GANTT_MIN_ZOOM = 0.25
GANTT_MAX_ZOOM = 6.0
GANTT_DEFAULT_ZOOM = 1.0

# Геометрия оси времени и подписей на диаграмме Ганта.
GANTT_HORIZON_MIN = 1
GANTT_AXIS_WIDTH = 1
GANTT_AXIS_Y_OFFSET = -16
GANTT_TICK_TOP_OFFSET = -22
GANTT_TICK_BOTTOM_OFFSET = -10
GANTT_TICK_TEXT_X_OFFSET = -7
GANTT_TICK_TEXT_Y_OFFSET = -40
GANTT_TASK_LABEL_X = 4
GANTT_TASK_LABEL_Y_OFFSET = -2

# Оформление прямоугольников задач и отметок дедлайна.
GANTT_BAR_BORDER_DARKEN = 120
GANTT_BAR_TEXT_X_OFFSET = 6
GANTT_BAR_TEXT_Y_OFFSET = 1
GANTT_DEADLINE_LINE_OFFSET = 4
GANTT_DEADLINE_LINE_WIDTH = 2
GANTT_DEADLINE_TEXT_X_OFFSET = 4
GANTT_DEADLINE_TEXT_Y_OFFSET = 1
GANTT_SCENE_BOTTOM_PADDING = 20

# Размер и оформление Matplotlib-графика.
PLOT_FIGURE_SIZE = (6, 2.4)
PLOT_SUBPLOT_CODE = 111
PLOT_GRID_ALPHA = 0.28

# Основная палитра приложения и диаграммы.
COLOR_BACKGROUND = "#f7f8fb"
COLOR_TEXT = "#111827"
COLOR_GROUP_BACKGROUND = "#ffffff"
COLOR_GROUP_BORDER = "#f7f8fb"
COLOR_INPUT_BORDER = "#f7f8fb"
COLOR_BUTTON = "#1d4ed8"
COLOR_BUTTON_BORDER = "#1d4ed8"
COLOR_BUTTON_HOVER = "#1d4ed8"
COLOR_BUTTON_DISABLED = "#94a3b8"
COLOR_HEADER_BACKGROUND = "#f7f8fb"
COLOR_GANTT_AXIS = "#4b5563"
COLOR_GANTT_TEXT = "#111827"
COLOR_GANTT_DONE = "#22c55e"
COLOR_GANTT_LATE = "#ef4444"
COLOR_GANTT_INNER_TEXT = "#ffffff"
COLOR_GANTT_DEADLINE_TEXT = "#374151"
COLOR_GANTT_DEADLINE_LINE = "#111827"

# Радиусы, отступы и CSS-параметры оформления.
GROUP_BORDER_RADIUS = 6
INPUT_BORDER_RADIUS = 4
BUTTON_BORDER_RADIUS = 5
GROUP_MARGIN_TOP = 10
GROUP_TITLE_LEFT_PADDING = 10
GROUP_TITLE_PADDING = "0 4px"
CONTROL_PADDING = "4px"
BUTTON_PADDING = "7px 12px"
HEADER_PADDING = "5px"
BASE_FONT_SIZE = 13